# [START container_helloapp_skaffold]
apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: hello-app
deploy:
  kubectl:
    manifests:
    - manifests/helloweb-deployment.yaml
    - manifests/helloweb-service-load-balancer.yaml
# profiles:
# - name: cloudbuild
#   build:
#     googleCloudBuild: {}
# [END container_helloapp_skaffold]
